import { SystemLanguageDto } from '../DTOs/systemLanguage.dto';
import { NAME_MAX_LEN, SHORTCUTS_MAX } from './settings';

export const languageOptions: SystemLanguageDto[] = [
    {
        label: 'English (EN)', value: 'en-US',
        newChat: "newChat", imageTag: "image", audioTag: "audio", textTag: "text", fileTag: "file", webSearch: "web search",
        promptTag: "Prompts", modelTag: "Models", currentModel: "Current Model", select: "Select", releaseDate: "Release Date",
        systemPrompt: "System Prompt", clear: "clear", save: "save", apply: "apply", verify: "Verify",
        verifyLabel: "The credit information will be displayed after the API key is verified.",
        credit: "Credit", totalCredits: "Total Credits", usedCredits: "Used Credits", refresh: "Refresh", saveChanges: "Save Changes",
        delete: "Delete", addNew: "Add", shortcuts: "Shortcuts", shortcutName: "Shortcut Name", shortcutPrompt: "Shortcut Prompt",
        shortcutMaxCount: `You can only add up to 5 shortcuts`, shortcutSaved: "Shortcuts saved successfully",
        shortcutDeleted: "Shortcut deleted successfully", saveUserInfo: "Save User Info", userName: "User Name",
        languagePreference: "Language Preference", setAvatar: "Set Avatar", updateAvatar: "Update Avatar", setting: "Setting",
        userInfo: "User Info", apiKeyTab: "API Key", userInfoTab: "User Info", shortcutsTab: "Shortcuts", aboutTab: "About",
        getName: "Your Name/Nick Name", inputPlaceholder: "Please input here..", selectPlaceholder: "Set System Language",
        noShortcuts: "No shortcuts yet, click 'Add' to get started", maxShortcutWarning: `You can only add up to ${SHORTCUTS_MAX} shortcuts`,
        shortcutNamePlaceholder: "e.g. Translate to English", shortcutPromptPlaceholder: "Input your prompt...",
        nameMaxWarning: `Name cannot exceed ${NAME_MAX_LEN} characters`, confirmDelete: "Are you sure to delete this shortcut?",
        deleteText: "Delete", cancelText: "Cancel", chatHistory: "Chat History", clearChatHistory: "Clear Chat History",
        clearHistoryConfirm: "Are you sure to clear chat history? This action cannot be undone.", historyCleared: "Chat history cleared",
        pinChat: "Pin Chat", unpinChat: "Unpin Chat", expand: "Expand", collapse: "Collapse", selectModel: "Select Model",
        noModelAvailable: "No model available", modelReleasedOn: "Released on", modelInputSupport: "Input Support",
        modelSystemPrompt: "System Prompt", modelFreeOnly: "Free Models Only", modelMultiFormatSupport: "Multi-format Input Support",
        noModelMatch: "No model matches the filter", selectLanguage: "Select Language", myPrompts: "My Prompts",
        prefabPrompts: "Prefab Prompts", promptName: "Prompt Name", promptContent: "Prompt Content",
        promptMaxCount: `You can only add up to ${SHORTCUTS_MAX} prompts`, promptSaved: "Prompt saved successfully",
        promptDeleted: "Prompt deleted successfully", savePromptChanges: "Save Prompt Changes", promptNamePlaceholder: "e.g. Translate to English",
        promptContentPlaceholder: "Input your prompt...", promptNameMaxWarning: `Prompt name cannot exceed ${NAME_MAX_LEN} characters`,
        confirmDeletePrompt: "Are you sure to delete this prompt?", modelSettings: "Model Settings",
        modelSettingsSaved: "Model settings saved successfully", promptHolder: "Create system prompt for the assistant...",
        operation: "Operation", selected: "Selected", enterToSubmit: "press Enter to submit", verifyFirst: "Please verify the API key first.",
        pricing: "Pricing", contextLength: "Context Length", usernamePlaceHolder: "Ennter your name/nick name here..",
        statistics: "Statistics", sponsorship: "Sponsorship", buyMeACoffee: "Buy me a Coffee",requestFailed:"Request Failed",success:"Success", 
        failed:"Failed",applyingFreeApiKey:"Applying for free API Key...",getFreeApiKey:"Get Free API-Key",freeApikeyTip:"The free API-KEY has no quota and cannot be recharged, but it can be used to access free large models. In the model interface, you can filter for free models to select them.",
        freeKeyApplySuccess:"Free Key applied successfully! Enjoy using free models.",verifySuccess:"API Key verified successfully",
        netWorkError:"Network error, please try again later",invalidKey:"Invalid API Key, please check and re-enter",
        image:"image",audio:"audio",file:"file",text:"text",userInfoUpdated:"User info updated successfully",userInfoUpdateFailed:"Failed to update user info",
        uploadFiles:"Upload files",uploadFilesTip:"Click and choose files to upload",modelOrFuctionUnavilable:"Current Model/Function is Unavailable",
    },
    {
        label: '简体中文 (ZH)', value: 'zh-CN',
        newChat: "新建对话", imageTag: "图片", audioTag: "音频", textTag: "文本", fileTag: "文件", webSearch: "网页搜索",
        promptTag: "提示词", modelTag: "模型", currentModel: "当前模型", select: "选择", releaseDate: "发布日期",
        systemPrompt: "系统提示词", clear: "清除", save: "保存", apply: "应用", verify: "验证",
        verifyLabel: "验证 API Key 后将显示额度信息。",
        credit: "额度", totalCredits: "总额度", usedCredits: "已用额度", refresh: "刷新", saveChanges: "保存修改",
        delete: "删除", addNew: "添加", shortcuts: "快捷方式", shortcutName: "快捷名称", shortcutPrompt: "快捷提示词",
        shortcutMaxCount: `最多只能添加 5 个快捷方式`, shortcutSaved: "快捷方式保存成功",
        shortcutDeleted: "快捷方式删除成功", saveUserInfo: "保存用户信息", userName: "用户名",
        languagePreference: "语言偏好", setAvatar: "设置头像", updateAvatar: "更新头像", setting: "设置",
        userInfo: "用户信息", apiKeyTab: "API Key", userInfoTab: "用户信息", shortcutsTab: "快捷方式", aboutTab: "关于",
        getName: "你的姓名/昵称", inputPlaceholder: "请输入..", selectPlaceholder: "设置系统语言",
        noShortcuts: "暂无快捷方式，点击“添加”开始", maxShortcutWarning: `最多只能添加 ${SHORTCUTS_MAX} 个快捷方式`,
        shortcutNamePlaceholder: "例如：翻译成英文", shortcutPromptPlaceholder: "请输入提示词...",
        nameMaxWarning: `名称不能超过 ${NAME_MAX_LEN} 个字符`, confirmDelete: "确认要删除该快捷方式吗？",
        deleteText: "删除", cancelText: "取消", chatHistory: "对话历史", clearChatHistory: "清除对话历史",
        clearHistoryConfirm: "确认清除对话历史？此操作不可撤销。", historyCleared: "对话历史已清除",
        pinChat: "置顶对话", unpinChat: "取消置顶", expand: "展开", collapse: "收起", selectModel: "选择模型",
        noModelAvailable: "暂无可用模型", modelReleasedOn: "发布于", modelInputSupport: "输入支持",
        modelSystemPrompt: "系统提示词", modelFreeOnly: "仅免费模型", modelMultiFormatSupport: "多格式输入支持",
        noModelMatch: "无符合条件的模型", selectLanguage: "选择语言", myPrompts: "我的提示词",
        prefabPrompts: "预设提示词", promptName: "提示词名称", promptContent: "提示词内容",
        promptMaxCount: `最多只能添加 ${SHORTCUTS_MAX} 个提示词`, promptSaved: "提示词保存成功",
        promptDeleted: "提示词删除成功", savePromptChanges: "保存修改", promptNamePlaceholder: "例如：翻译成英文",
        promptContentPlaceholder: "请输入提示词...", promptNameMaxWarning: `提示词名称不能超过 ${NAME_MAX_LEN} 个字符`,
        confirmDeletePrompt: "确认要删除该提示词吗？", modelSettings: "模型设置",
        modelSettingsSaved: "模型设置保存成功", promptHolder: "为助手创建系统提示词...",
        operation: "操作", selected: "已选", enterToSubmit: "按 Enter 提交", verifyFirst: "请先验证 API Key。",
        pricing: "价格", contextLength: "上下文长度", usernamePlaceHolder: "请输入姓名/昵称..",
        statistics: "统计", sponsorship: "赞助", buyMeACoffee: "请我喝咖啡", requestFailed:"请求失败", success:"成功", 
        failed:"失败", applyingFreeApiKey:"申请免费 API Key...", getFreeApiKey:"获取免费 API Key", freeApikeyTip:"免费 API Key 无额度限制，但不可充值。可用于访问免费大模型。在模型界面可筛选免费模型。",
        freeKeyApplySuccess:"免费 Key 申请成功！尽情使用免费模型吧。", verifySuccess:"API Key 验证成功",
        netWorkError:"网络错误，请稍后再试", invalidKey:"API Key 无效，请检查后重新输入",
        image:"图片", audio:"音频", file:"文件", text:"文本", userInfoUpdated:"用户信息更新成功", userInfoUpdateFailed:"用户信息更新失败",
        uploadFiles:"上传文件", uploadFilesTip:"点击选择文件上传", modelOrFuctionUnavilable:"当前模型/功能不可用",
    },
    {
        label: 'Español (ES)', value: 'es-ES',
        newChat: "nuevoChat", imageTag: "imagen", audioTag: "audio", textTag: "texto", fileTag: "archivo", webSearch: "búsqueda web",
        promptTag: "Prompts", modelTag: "Modelos", currentModel: "Modelo Actual", select: "Seleccionar", releaseDate: "Fecha de Lanzamiento",
        systemPrompt: "Prompt del Sistema", clear: "limpiar", save: "guardar", apply: "aplicar", verify: "Verificar",
        verifyLabel: "La información de créditos se mostrará tras verificar la clave API.",
        credit: "Crédito", totalCredits: "Créditos Totales", usedCredits: "Créditos Usados", refresh: "Actualizar", saveChanges: "Guardar Cambios",
        delete: "Eliminar", addNew: "Añadir", shortcuts: "Atajos", shortcutName: "Nombre del Atajo", shortcutPrompt: "Prompt del Atajo",
        shortcutMaxCount: `Solo puedes añadir hasta 5 atajos`, shortcutSaved: "Atajos guardados con éxito",
        shortcutDeleted: "Atajo eliminado con éxito", saveUserInfo: "Guardar Info de Usuario", userName: "Nombre de Usuario",
        languagePreference: "Idioma Preferido", setAvatar: "Configurar Avatar", updateAvatar: "Actualizar Avatar", setting: "Configuración",
        userInfo: "Info de Usuario", apiKeyTab: "Clave API", userInfoTab: "Usuario", shortcutsTab: "Atajos", aboutTab: "Acerca de",
        getName: "Tu Nombre/Apodo", inputPlaceholder: "Por favor escribe aquí..", selectPlaceholder: "Seleccionar Idioma del Sistema",
        noShortcuts: "Sin atajos aún, haz clic en 'Añadir' para comenzar", maxShortcutWarning: `Solo puedes añadir hasta ${SHORTCUTS_MAX} atajos`,
        shortcutNamePlaceholder: "ej. Traducir al inglés", shortcutPromptPlaceholder: "Escribe tu prompt...",
        nameMaxWarning: `El nombre no puede exceder ${NAME_MAX_LEN} caracteres`, confirmDelete: "¿Seguro que quieres eliminar este atajo?",
        deleteText: "Eliminar", cancelText: "Cancelar", chatHistory: "Historial de Chat", clearChatHistory: "Borrar Historial de Chat",
        clearHistoryConfirm: "¿Seguro que quieres borrar el historial de chat? Esta acción no se puede deshacer.", historyCleared: "Historial borrado",
        pinChat: "Fijar Chat", unpinChat: "Desfijar Chat", expand: "Expandir", collapse: "Colapsar", selectModel: "Seleccionar Modelo",
        noModelAvailable: "No hay modelos disponibles", modelReleasedOn: "Lanzado en", modelInputSupport: "Soporte de Entrada",
        modelSystemPrompt: "Prompt del Sistema", modelFreeOnly: "Solo Modelos Gratis", modelMultiFormatSupport: "Soporte Multi-formato",
        noModelMatch: "Ningún modelo coincide con el filtro", selectLanguage: "Seleccionar Idioma", myPrompts: "Mis Prompts",
        prefabPrompts: "Prompts Predefinidos", promptName: "Nombre del Prompt", promptContent: "Contenido del Prompt",
        promptMaxCount: `Solo puedes añadir hasta ${SHORTCUTS_MAX} prompts`, promptSaved: "Prompt guardado con éxito",
        promptDeleted: "Prompt eliminado con éxito", savePromptChanges: "Guardar Cambios", promptNamePlaceholder: "ej. Traducir al inglés",
        promptContentPlaceholder: "Escribe tu prompt...", promptNameMaxWarning: `El nombre del prompt no puede exceder ${NAME_MAX_LEN} caracteres`,
        confirmDeletePrompt: "¿Seguro que quieres eliminar este prompt?", modelSettings: "Configuración del Modelo",
        modelSettingsSaved: "Configuración guardada con éxito", promptHolder: "Crea prompt del sistema para el asistente...",
        operation: "Operación", selected: "Seleccionado", enterToSubmit: "presiona Enter para enviar", verifyFirst: "Por favor verifica la clave API primero.",
        pricing: "Precios", contextLength: "Longitud del Contexto", usernamePlaceHolder: "Escribe tu nombre/apodo aquí..",
        statistics: "Estadísticas", sponsorship: "Patrocinio", buyMeACoffee: "Invítame un café",requestFailed:"Solicitud Fallida",success:"Éxito", 
        failed:"Fallido",applyingFreeApiKey:"Solicitando Clave API gratuita...",getFreeApiKey:"Obtener Clave API Gratis",freeApikeyTip:"La clave API gratuita no tiene cuota y no se puede recargar, pero permite usar modelos gratuitos. En la interfaz puedes filtrar por modelos gratis.",
        freeKeyApplySuccess:"¡Clave gratuita solicitada con éxito! Disfruta los modelos gratis.",verifySuccess:"Clave API verificada con éxito",
        netWorkError:"Error de red, por favor inténtalo más tarde",invalidKey:"Clave API inválida, revisa y reingresa",
        image:"imagen",audio:"audio",file:"archivo",text:"texto",userInfoUpdated:"Usuario actualizado con éxito",userInfoUpdateFailed:"Error al actualizar usuario",
        uploadFiles:"Subir archivos",uploadFilesTip:"Haz clic y elige archivos para subir",modelOrFuctionUnavilable:"Modelo/Función no disponible",
    },
     {
        label: 'Français (FR)', value: 'fr-FR',
        newChat: "Nouvelle discussion", imageTag: "image", audioTag: "audio", textTag: "texte", fileTag: "fichier", webSearch: "recherche web",
        promptTag: "Prompts", modelTag: "Modèles", currentModel: "Modèle actuel", select: "Sélectionner", releaseDate: "Date de sortie",
        systemPrompt: "Invite système", clear: "effacer", save: "sauvegarder", apply: "appliquer", verify: "Vérifier",
        verifyLabel: "Les informations de crédit seront affichées après vérification de la clé API.",
        credit: "Crédit", totalCredits: "Crédits totaux", usedCredits: "Crédits utilisés", refresh: "Rafraîchir", saveChanges: "Sauvegarder",
        delete: "Supprimer", addNew: "Ajouter", shortcuts: "Raccourcis", shortcutName: "Nom du raccourci", shortcutPrompt: "Invite du raccourci",
        shortcutMaxCount: `Vous pouvez ajouter jusqu'à 5 raccourcis`, shortcutSaved: "Raccourcis enregistrés", 
        shortcutDeleted: "Raccourci supprimé", saveUserInfo: "Enregistrer infos", userName: "Nom d'utilisateur",
        languagePreference: "Langue", setAvatar: "Définir avatar", updateAvatar: "Mettre à jour avatar", setting: "Paramètres",
        userInfo: "Infos utilisateur", apiKeyTab: "Clé API", userInfoTab: "Utilisateur", shortcutsTab: "Raccourcis", aboutTab: "À propos",
        getName: "Votre nom/pseudo", inputPlaceholder: "Veuillez entrer ici..", selectPlaceholder: "Définir la langue système",
        noShortcuts: "Aucun raccourci, cliquez sur 'Ajouter' pour commencer", maxShortcutWarning: `Vous pouvez ajouter jusqu'à ${SHORTCUTS_MAX} raccourcis`,
        shortcutNamePlaceholder: "ex. Traduire en français", shortcutPromptPlaceholder: "Entrez votre prompt...",
        nameMaxWarning: `Le nom ne peut dépasser ${NAME_MAX_LEN} caractères`, confirmDelete: "Supprimer ce raccourci ?",
        deleteText: "Supprimer", cancelText: "Annuler", chatHistory: "Historique", clearChatHistory: "Effacer l'historique",
        clearHistoryConfirm: "Effacer l'historique ? Action irréversible.", historyCleared: "Historique effacé",
        pinChat: "Épingler", unpinChat: "Désépingler", expand: "Développer", collapse: "Réduire", selectModel: "Choisir modèle",
        noModelAvailable: "Aucun modèle", modelReleasedOn: "Publié le", modelInputSupport: "Support d'entrée",
        modelSystemPrompt: "Invite système", modelFreeOnly: "Modèles gratuits", modelMultiFormatSupport: "Support multi-format",
        noModelMatch: "Aucun modèle trouvé", selectLanguage: "Choisir langue", myPrompts: "Mes invites",
        prefabPrompts: "Invites prêtes", promptName: "Nom de l'invite", promptContent: "Contenu",
        promptMaxCount: `Vous pouvez ajouter jusqu'à ${SHORTCUTS_MAX} invites`, promptSaved: "Invite enregistrée",
        promptDeleted: "Invite supprimée", savePromptChanges: "Enregistrer modifications", promptNamePlaceholder: "ex. Traduire en français",
        promptContentPlaceholder: "Entrez votre invite...", promptNameMaxWarning: `Le nom ne peut dépasser ${NAME_MAX_LEN} caractères`,
        confirmDeletePrompt: "Supprimer cette invite ?", modelSettings: "Paramètres modèle",
        modelSettingsSaved: "Paramètres enregistrés", promptHolder: "Créer une invite système...",
        operation: "Opération", selected: "Sélectionné", enterToSubmit: "Appuyez sur Entrée pour valider", verifyFirst: "Veuillez vérifier la clé API.",
        pricing: "Tarifs", contextLength: "Longueur contexte", usernamePlaceHolder: "Entrez votre nom/pseudo...",
        statistics: "Statistiques", sponsorship: "Parrainage", buyMeACoffee: "Offrez-moi un café",requestFailed:"Échec",success:"Succès", 
        failed:"Échoué",applyingFreeApiKey:"Demande de clé API gratuite...",getFreeApiKey:"Obtenir clé gratuite",freeApikeyTip:"La clé gratuite n'a pas de quota et ne peut pas être rechargée. Elle permet d'utiliser des modèles gratuits.",
        freeKeyApplySuccess:"Clé gratuite obtenue !",verifySuccess:"Clé API vérifiée",
        netWorkError:"Erreur réseau",invalidKey:"Clé invalide",image:"image",audio:"audio",file:"fichier",text:"texte",
        userInfoUpdated:"Infos mises à jour",userInfoUpdateFailed:"Échec de mise à jour",
        uploadFiles:"Téléverser fichiers",uploadFilesTip:"Cliquez pour choisir des fichiers",modelOrFuctionUnavilable:"Modèle/Fonction indisponible",
    },
    {
        label: '日本語 (JA)', value: 'ja-JP',
        newChat: "新規チャット", imageTag: "画像", audioTag: "音声", textTag: "テキスト", fileTag: "ファイル", webSearch: "ウェブ検索",
        promptTag: "プロンプト", modelTag: "モデル", currentModel: "現在のモデル", select: "選択", releaseDate: "リリース日",
        systemPrompt: "システムプロンプト", clear: "クリア", save: "保存", apply: "適用", verify: "確認",
        verifyLabel: "APIキー確認後にクレジット情報が表示されます。",
        credit: "クレジット", totalCredits: "総クレジット", usedCredits: "使用済み", refresh: "更新", saveChanges: "変更を保存",
        delete: "削除", addNew: "追加", shortcuts: "ショートカット", shortcutName: "名前", shortcutPrompt: "プロンプト",
        shortcutMaxCount: `ショートカットは最大5件まで`, shortcutSaved: "保存しました", shortcutDeleted: "削除しました",
        saveUserInfo: "ユーザー情報保存", userName: "ユーザー名", languagePreference: "言語設定",
        setAvatar: "アバター設定", updateAvatar: "アバター更新", setting: "設定", userInfo: "ユーザー情報",
        apiKeyTab: "APIキー", userInfoTab: "ユーザー", shortcutsTab: "ショートカット", aboutTab: "情報",
        getName: "名前/ニックネーム", inputPlaceholder: "ここに入力してください..", selectPlaceholder: "システム言語設定",
        noShortcuts: "ショートカットなし、「追加」をクリック", maxShortcutWarning: `ショートカットは最大${SHORTCUTS_MAX}件まで`,
        shortcutNamePlaceholder: "例: 英語に翻訳", shortcutPromptPlaceholder: "プロンプトを入力...",
        nameMaxWarning: `名前は${NAME_MAX_LEN}文字以内`, confirmDelete: "削除しますか？",
        deleteText: "削除", cancelText: "キャンセル", chatHistory: "履歴", clearChatHistory: "履歴をクリア",
        clearHistoryConfirm: "履歴を削除しますか？ 元に戻せません。", historyCleared: "履歴削除済み",
        pinChat: "固定", unpinChat: "固定解除", expand: "展開", collapse: "折りたたみ", selectModel: "モデル選択",
        noModelAvailable: "利用不可", modelReleasedOn: "リリース", modelInputSupport: "入力対応",
        modelSystemPrompt: "システムプロンプト", modelFreeOnly: "無料のみ", modelMultiFormatSupport: "マルチ入力対応",
        noModelMatch: "一致なし", selectLanguage: "言語選択", myPrompts: "マイプロンプト",
        prefabPrompts: "プリセット", promptName: "名前", promptContent: "内容",
        promptMaxCount: `プロンプトは最大${SHORTCUTS_MAX}件まで`, promptSaved: "保存しました",
        promptDeleted: "削除しました", savePromptChanges: "変更を保存", promptNamePlaceholder: "例: 英語に翻訳",
        promptContentPlaceholder: "プロンプトを入力...", promptNameMaxWarning: `名前は${NAME_MAX_LEN}文字以内`,
        confirmDeletePrompt: "削除しますか？", modelSettings: "モデル設定",
        modelSettingsSaved: "保存しました", promptHolder: "システムプロンプトを作成...",
        operation: "操作", selected: "選択中", enterToSubmit: "Enterで送信", verifyFirst: "先にAPIキーを確認してください。",
        pricing: "料金", contextLength: "文脈長", usernamePlaceHolder: "名前/ニックネームを入力..",
        statistics: "統計", sponsorship: "スポンサー", buyMeACoffee: "コーヒーを奢る",requestFailed:"失敗",success:"成功", 
        failed:"エラー",applyingFreeApiKey:"無料キー申請中...",getFreeApiKey:"無料キー取得",freeApikeyTip:"無料キーは無制限ですが、課金不可。無料モデルに使用可能。",
        freeKeyApplySuccess:"無料キー取得成功",verifySuccess:"キー確認成功",
        netWorkError:"ネットワークエラー",invalidKey:"無効なキー",image:"画像",audio:"音声",file:"ファイル",text:"テキスト",
        userInfoUpdated:"更新成功",userInfoUpdateFailed:"更新失敗",
        uploadFiles:"ファイルアップロード",uploadFilesTip:"クリックして選択",modelOrFuctionUnavilable:"モデル/機能利用不可",
    },
    {
        label: 'Deutsch (DE)', value: 'de-DE',
        newChat: "Neuer Chat", imageTag: "Bild", audioTag: "Audio", textTag: "Text", fileTag: "Datei", webSearch: "Websuche",
        promptTag: "Prompts", modelTag: "Modelle", currentModel: "Aktuelles Modell", select: "Auswählen", releaseDate: "Veröffentlichung",
        systemPrompt: "Systemprompt", clear: "Leeren", save: "Speichern", apply: "Anwenden", verify: "Prüfen",
        verifyLabel: "Kreditinformationen werden nach API-Key-Prüfung angezeigt.",
        credit: "Guthaben", totalCredits: "Gesamt", usedCredits: "Verbraucht", refresh: "Aktualisieren", saveChanges: "Änderungen speichern",
        delete: "Löschen", addNew: "Hinzufügen", shortcuts: "Shortcuts", shortcutName: "Name", shortcutPrompt: "Prompt",
        shortcutMaxCount: `Maximal 5 Shortcuts`, shortcutSaved: "Shortcut gespeichert", shortcutDeleted: "Shortcut gelöscht",
        saveUserInfo: "Infos speichern", userName: "Benutzername", languagePreference: "Sprache",
        setAvatar: "Avatar setzen", updateAvatar: "Avatar ändern", setting: "Einstellungen", userInfo: "Benutzerinfo",
        apiKeyTab: "API-Key", userInfoTab: "Benutzer", shortcutsTab: "Shortcuts", aboutTab: "Über",
        getName: "Name/Spitzname", inputPlaceholder: "Hier eingeben..", selectPlaceholder: "Systemsprache wählen",
        noShortcuts: "Keine Shortcuts, klicken Sie auf 'Hinzufügen'", maxShortcutWarning: `Maximal ${SHORTCUTS_MAX} Shortcuts`,
        shortcutNamePlaceholder: "z.B. Übersetze ins Deutsche", shortcutPromptPlaceholder: "Prompt eingeben...",
        nameMaxWarning: `Name darf max. ${NAME_MAX_LEN} Zeichen haben`, confirmDelete: "Shortcut löschen?",
        deleteText: "Löschen", cancelText: "Abbrechen", chatHistory: "Chatverlauf", clearChatHistory: "Verlauf löschen",
        clearHistoryConfirm: "Verlauf wirklich löschen? Nicht rückgängig.", historyCleared: "Verlauf gelöscht",
        pinChat: "Anheften", unpinChat: "Lösen", expand: "Erweitern", collapse: "Einklappen", selectModel: "Modell wählen",
        noModelAvailable: "Kein Modell", modelReleasedOn: "Veröffentlicht", modelInputSupport: "Eingabeunterstützung",
        modelSystemPrompt: "Systemprompt", modelFreeOnly: "Nur frei", modelMultiFormatSupport: "Multiformat",
        noModelMatch: "Kein Treffer", selectLanguage: "Sprache wählen", myPrompts: "Meine Prompts",
        prefabPrompts: "Vorlagen", promptName: "Name", promptContent: "Inhalt",
        promptMaxCount: `Maximal ${SHORTCUTS_MAX} Prompts`, promptSaved: "Prompt gespeichert",
        promptDeleted: "Prompt gelöscht", savePromptChanges: "Änderungen speichern", promptNamePlaceholder: "z.B. Übersetze ins Deutsche",
        promptContentPlaceholder: "Prompt eingeben...", promptNameMaxWarning: `Name darf max. ${NAME_MAX_LEN} Zeichen haben`,
        confirmDeletePrompt: "Prompt löschen?", modelSettings: "Modell-Einstellungen",
        modelSettingsSaved: "Gespeichert", promptHolder: "Systemprompt erstellen...",
        operation: "Aktion", selected: "Ausgewählt", enterToSubmit: "Enter zum Senden", verifyFirst: "Bitte API-Key prüfen.",
        pricing: "Preise", contextLength: "Kontextlänge", usernamePlaceHolder: "Namen/Spitznamen eingeben..",
        statistics: "Statistik", sponsorship: "Sponsoring", buyMeACoffee: "Kaffee spendieren",requestFailed:"Fehlgeschlagen",success:"Erfolg", 
        failed:"Fehler",applyingFreeApiKey:"Kostenlosen Key beantragen...",getFreeApiKey:"Gratis Key holen",freeApikeyTip:"Kostenloser Key ohne Aufladung. Nur für freie Modelle.",
        freeKeyApplySuccess:"Gratis Key erfolgreich!",verifySuccess:"API-Key geprüft",
        netWorkError:"Netzwerkfehler",invalidKey:"Ungültiger Key",image:"Bild",audio:"Audio",file:"Datei",text:"Text",
        userInfoUpdated:"Gespeichert",userInfoUpdateFailed:"Fehler beim Speichern",
        uploadFiles:"Dateien hochladen",uploadFilesTip:"Zum Hochladen klicken",modelOrFuctionUnavilable:"Modell/Funktion nicht verfügbar",
    },
    {
        label: 'Русский (RU)', value: 'ru-RU',
        newChat: "Новый чат", imageTag: "Изображение", audioTag: "Аудио", textTag: "Текст", fileTag: "Файл", webSearch: "Веб-поиск",
        promptTag: "Подсказки", modelTag: "Модели", currentModel: "Текущая модель", select: "Выбрать", releaseDate: "Дата выпуска",
        systemPrompt: "Системный запрос", clear: "Очистить", save: "Сохранить", apply: "Применить", verify: "Проверить",
        verifyLabel: "Информация о кредите появится после проверки API-ключа.",
        credit: "Кредиты", totalCredits: "Всего", usedCredits: "Использовано", refresh: "Обновить", saveChanges: "Сохранить изменения",
        delete: "Удалить", addNew: "Добавить", shortcuts: "Ярлыки", shortcutName: "Название", shortcutPrompt: "Подсказка",
        shortcutMaxCount: `Можно до 5 ярлыков`, shortcutSaved: "Сохранено", shortcutDeleted: "Удалено",
        saveUserInfo: "Сохранить данные", userName: "Имя пользователя", languagePreference: "Язык",
        setAvatar: "Установить аватар", updateAvatar: "Обновить аватар", setting: "Настройки", userInfo: "Пользователь",
        apiKeyTab: "API-ключ", userInfoTab: "Профиль", shortcutsTab: "Ярлыки", aboutTab: "О программе",
        getName: "Имя/ник", inputPlaceholder: "Введите здесь..", selectPlaceholder: "Выберите язык системы",
        noShortcuts: "Нет ярлыков, нажмите 'Добавить'", maxShortcutWarning: `До ${SHORTCUTS_MAX} ярлыков`,
        shortcutNamePlaceholder: "Напр. Перевести на русский", shortcutPromptPlaceholder: "Введите подсказку...",
        nameMaxWarning: `Имя не более ${NAME_MAX_LEN} символов`, confirmDelete: "Удалить ярлык?",
        deleteText: "Удалить", cancelText: "Отмена", chatHistory: "История", clearChatHistory: "Очистить историю",
        clearHistoryConfirm: "Очистить историю? Действие необратимо.", historyCleared: "История удалена",
        pinChat: "Закрепить", unpinChat: "Открепить", expand: "Развернуть", collapse: "Свернуть", selectModel: "Выбрать модель",
        noModelAvailable: "Нет модели", modelReleasedOn: "Выпущено", modelInputSupport: "Поддержка ввода",
        modelSystemPrompt: "Системный запрос", modelFreeOnly: "Только бесплатные", modelMultiFormatSupport: "Мультиформат",
        noModelMatch: "Совпадений нет", selectLanguage: "Выбрать язык", myPrompts: "Мои подсказки",
        prefabPrompts: "Шаблоны", promptName: "Название", promptContent: "Содержание",
        promptMaxCount: `До ${SHORTCUTS_MAX} подсказок`, promptSaved: "Сохранено",
        promptDeleted: "Удалено", savePromptChanges: "Сохранить изменения", promptNamePlaceholder: "Напр. Перевести на русский",
        promptContentPlaceholder: "Введите подсказку...", promptNameMaxWarning: `Имя не более ${NAME_MAX_LEN} символов`,
        confirmDeletePrompt: "Удалить подсказку?", modelSettings: "Настройки модели",
        modelSettingsSaved: "Сохранено", promptHolder: "Создать системный запрос...",
        operation: "Действие", selected: "Выбрано", enterToSubmit: "Enter для отправки", verifyFirst: "Сначала проверьте API-ключ.",
        pricing: "Цены", contextLength: "Длина контекста", usernamePlaceHolder: "Введите имя/ник..",
        statistics: "Статистика", sponsorship: "Поддержка", buyMeACoffee: "Угостить кофе",requestFailed:"Ошибка",success:"Успех", 
        failed:"Неудача",applyingFreeApiKey:"Запрос ключа...",getFreeApiKey:"Получить ключ",freeApikeyTip:"Бесплатный ключ без лимита. Только для бесплатных моделей.",
        freeKeyApplySuccess:"Ключ получен!",verifySuccess:"API-ключ проверен",
        netWorkError:"Ошибка сети",invalidKey:"Неверный ключ",image:"Изобр.",audio:"Аудио",file:"Файл",text:"Текст",
        userInfoUpdated:"Обновлено",userInfoUpdateFailed:"Ошибка обновления",
        uploadFiles:"Загрузить файлы",uploadFilesTip:"Нажмите для выбора",modelOrFuctionUnavilable:"Модель/функция недоступна",
    },
    {
        label: 'العربية (AR)', value: 'ar-SA',
        newChat: "محادثة جديدة", imageTag: "صورة", audioTag: "صوت", textTag: "نص", fileTag: "ملف", webSearch: "بحث ويب",
        promptTag: "أوامر", modelTag: "نماذج", currentModel: "النموذج الحالي", select: "اختيار", releaseDate: "تاريخ الإصدار",
        systemPrompt: "أمر النظام", clear: "مسح", save: "حفظ", apply: "تطبيق", verify: "تحقق",
        verifyLabel: "سيظهر رصيدك بعد التحقق من مفتاح API.",
        credit: "رصيد", totalCredits: "إجمالي", usedCredits: "مستخدم", refresh: "تحديث", saveChanges: "حفظ التغييرات",
        delete: "حذف", addNew: "إضافة", shortcuts: "اختصارات", shortcutName: "اسم", shortcutPrompt: "أمر",
        shortcutMaxCount: `يمكن إضافة 5 اختصارات فقط`, shortcutSaved: "تم الحفظ", shortcutDeleted: "تم الحذف",
        saveUserInfo: "حفظ البيانات", userName: "اسم المستخدم", languagePreference: "اللغة",
        setAvatar: "تعيين صورة", updateAvatar: "تحديث الصورة", setting: "الإعدادات", userInfo: "معلومات المستخدم",
        apiKeyTab: "مفتاح API", userInfoTab: "المستخدم", shortcutsTab: "اختصارات", aboutTab: "حول",
        getName: "الاسم/اللقب", inputPlaceholder: "أدخل هنا..", selectPlaceholder: "اختر لغة النظام",
        noShortcuts: "لا اختصارات، اضغط 'إضافة'", maxShortcutWarning: `يمكنك إضافة حتى ${SHORTCUTS_MAX} اختصار`,
        shortcutNamePlaceholder: "مثال: ترجم للعربية", shortcutPromptPlaceholder: "أدخل الأمر...",
        nameMaxWarning: `الاسم لا يتجاوز ${NAME_MAX_LEN} حرف`, confirmDelete: "حذف الاختصار؟",
        deleteText: "حذف", cancelText: "إلغاء", chatHistory: "السجل", clearChatHistory: "مسح السجل",
        clearHistoryConfirm: "هل تريد مسح السجل؟ لا رجوع.", historyCleared: "تم المسح",
        pinChat: "تثبيت", unpinChat: "إلغاء التثبيت", expand: "توسيع", collapse: "طي", selectModel: "اختر نموذج",
        noModelAvailable: "لا يوجد", modelReleasedOn: "صدر في", modelInputSupport: "يدعم الإدخال",
        modelSystemPrompt: "أمر النظام", modelFreeOnly: "مجاني فقط", modelMultiFormatSupport: "متعدد الصيغ",
        noModelMatch: "لا نتائج", selectLanguage: "اختر اللغة", myPrompts: "أوامري",
        prefabPrompts: "جاهزة", promptName: "اسم", promptContent: "محتوى",
        promptMaxCount: `يمكن إضافة ${SHORTCUTS_MAX} أوامر فقط`, promptSaved: "تم الحفظ",
        promptDeleted: "تم الحذف", savePromptChanges: "حفظ التغييرات", promptNamePlaceholder: "مثال: ترجم للعربية",
        promptContentPlaceholder: "أدخل الأمر...", promptNameMaxWarning: `الاسم لا يتجاوز ${NAME_MAX_LEN} حرف`,
        confirmDeletePrompt: "حذف الأمر؟", modelSettings: "إعدادات النموذج",
        modelSettingsSaved: "تم الحفظ", promptHolder: "أنشئ أمر نظام...",
        operation: "عملية", selected: "محدد", enterToSubmit: "اضغط Enter للإرسال", verifyFirst: "تحقق من مفتاح API أولا.",
        pricing: "الأسعار", contextLength: "طول السياق", usernamePlaceHolder: "أدخل اسمك/لقبك..",
        statistics: "إحصائيات", sponsorship: "دعم", buyMeACoffee: "اشترِ لي قهوة",requestFailed:"فشل",success:"نجاح", 
        failed:"خطأ",applyingFreeApiKey:"طلب مفتاح مجاني...",getFreeApiKey:"احصل على مفتاح مجاني",freeApikeyTip:"المفتاح المجاني بلا حد. يستخدم للنماذج المجانية فقط.",
        freeKeyApplySuccess:"تم الحصول على مفتاح مجاني",verifySuccess:"تم التحقق من المفتاح",
        netWorkError:"خطأ في الشبكة",invalidKey:"مفتاح غير صالح",image:"صورة",audio:"صوت",file:"ملف",text:"نص",
        userInfoUpdated:"تم التحديث",userInfoUpdateFailed:"فشل التحديث",
        uploadFiles:"رفع ملفات",uploadFilesTip:"اضغط لاختيار ملفات",modelOrFuctionUnavilable:"النموذج/الوظيفة غير متاحة",
    }
]