// language.dto.ts

export interface SystemLanguageDto {
  label: string;
  value: string;
  newChat: string;
  imageTag: string;
  audioTag: string;
  textTag: string;
  fileTag: string;
  webSearch: string;
  promptTag: string;
  modelTag: string;
  currentModel: string;
  select: string;
  releaseDate: string;
  systemPrompt: string;
  clear: string;
  save: string;
  apply: string;
  verify: string;
  verifyLabel: string;
  credit: string;
  totalCredits: string;
  usedCredits: string;
  refresh: string;
  saveChanges: string;
  delete: string;
  addNew: string;
  shortcuts: string;
  shortcutName: string;
  shortcutPrompt: string;
  shortcutMaxCount: string;
  shortcutSaved: string;
  shortcutDeleted: string;
  saveUserInfo: string;
  userName: string;
  languagePreference: string;
  setAvatar: string;
  updateAvatar: string;
  setting: string;
  userInfo: string;
  apiKeyTab: string;
  userInfoTab: string;
  shortcutsTab: string;
  aboutTab: string;
  getName: string;
  inputPlaceholder: string;
  selectPlaceholder: string;
  noShortcuts: string;
  maxShortcutWarning: string;
  shortcutNamePlaceholder: string;
  shortcutPromptPlaceholder: string;
  nameMaxWarning: string;
  confirmDelete: string;
  deleteText: string;
  cancelText: string;
  chatHistory: string;
  clearChatHistory: string;
  clearHistoryConfirm: string;
  historyCleared: string;
  pinChat: string;
  unpinChat: string;
  expand: string;
  collapse: string;
  selectModel: string;
  noModelAvailable: string;
  modelReleasedOn: string;
  modelInputSupport: string;
  modelSystemPrompt: string;
  modelFreeOnly: string;
  modelMultiFormatSupport: string;
  noModelMatch: string;
  selectLanguage: string;
  myPrompts: string;
  prefabPrompts: string;
  promptName: string;
  promptContent: string;
  promptMaxCount: string;
  promptSaved: string;
  promptDeleted: string;
  savePromptChanges: string;
  promptNamePlaceholder: string;
  promptContentPlaceholder: string;
  promptNameMaxWarning: string;
  confirmDeletePrompt: string;
  modelSettings: string;
  modelSettingsSaved: string;
  promptHolder: string;
  operation: string;
  selected:string;
  enterToSubmit:string;
    verifyFirst:string;
    pricing:string;
    contextLength:string;
    usernamePlaceHolder:string;
    statistics:string;
    sponsorship:string;
    buyMeACoffee:string;
}

export interface  UserInfo {
    name: string;
    language: SystemLanguageDto;
    avatar: string; // dataURL 或本地路径；为空时显示默认灰头像
};